# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
dist: bionic

language: R
sudo: required

compiler:
  - clang

cache: packages

jobs:
  include:
    - name: gcc-8
      env: CXX11="g++-8" CXX17="g++-8" CC="gcc-8"
    - name: gcc-9
      env: CXX11="g++-9" CXX17="g++-9" CC="gcc-9"
    - name: gcc-10
      env: CXX11="g++-10" CXX17="g++-10" CC="gcc-10"

before_install:
addons:
  apt:
    update: false
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - build-essential
    - ${CXX17}

warnings_are_errors: false
