# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
addons:
  apt:
    update: false
    packages:
      - clang++-6.0
      - libstdc++6
      - g++-7

  env:
    - MATRIX_EVAL="CC=clang-6.0 && CXX=clang-6.0"
    - LINKER_FLAGS="-stdlib=libstdc++"

warnings_are_errors: false
