# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
dist: bionic

language: r
sudo: required

env:
  global:
    - R_VERSION="4.0"

cache: packages

jobs:
  include:
      env: CXX11="g++-10" CXX17="g++-10" CC="gcc-10"

before_install:
  - sudo apt-get install ${CXX17} r-cran-rcpp r-cran-bit64 r-cran-tinytest
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/${CC} 60 --slave /usr/bin/g++ g++ /usr/bin/${CXX17}
  - g++ --version

addons:
  apt:
    update: false
  sources:
    - ubuntu-toolchain-r-test
  packages:
    - build-essential
    - ${CXX17}

warnings_are_errors: false
