# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
dist: focal

language: r
cache: packages

env:
  global:
    - R_VERSION="4.0"

r_binary_packages:
  - RcppSimdJson
  - dplyr
  - purrr
  - glue
  - jsonlite
  - httr
  - assertive
  - stringr
  - utils
  - readxl
  - readr
  - rvest
  - lubridate
  - tidyr
  - xml2
  - textclean

warnings_are_errors: false
