# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
dist: focal

language: r
cache: packages

env:
  global:
    - R_VERSION="4.0"

r_binary_packages:
    - RcppSimdJson

before_install:
addons:
  apt:
    update: true
  sources:
    - ubuntu-toolchain-r-test

warnings_are_errors: false
