# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
cache: packages

before_install:
addons:
  apt:
    update: false
    packages:
      - clang++-6.0
      - g++-7

warnings_are_errors: false
