# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
dist: focal

language: R
cache: packages

before_install:
addons:
  apt:
    update: true

warnings_are_errors: false
