# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

os: linux
dist: focal

language: r
cache: packages
sudo: required

env:
  global:
    - R_VERSION="4.0"

before_install:
addons:
  r_binary_packages:
    - RcppSimdJson

warnings_are_errors: false
